# Site settings
title: bgran.de
email: hey@bgran.de
description: >
  Chronicles of a biochemist-turned-computational biologist
  working in cancer genomics.
baseurl: ""
url: "http://bgran.de"
twitter_username: grandebruno
github_username:  brunogrande

# Post settings
excerpt_separator: <!--more-->

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      read_more: true

# Build settings
markdown: kramdown
permalink: /:title/
future: true
